package tryanko.test.com.wordgame

enum class ViewIDEnum(val id: Int) {
    PLAYER_1_EDIT_TEXT_ID(1),
    PLAYER_2_EDIT_TEXT_ID(2),
    START_WORD_EDIT_TEXT_ID(3),
    CURRENT_WORD_TEXT_VIEW_ID(4),
    GAME_FIELD_GRID_LAYOUT_ID(5),
    PLAYER_1_NAME_TEXT_VIEW_ID(6),
    PLAYER_2_NAME_TEXT_VIEW_ID(7),
    BTN_OK_BUTTON_ID(8),
    BTN_ROLLBACK_BUTTON_ID(9),
    BTN_PASS_ID(10),
    BTN_SHOW_WORD_LIST_ID(11)
}